"use client"

// import type { Metadata } from "next";
import Header from "@/Components/Header";
import { useState } from "react";


// export const metadata: Metadata = {
//   title: {
//     default: "Authentication Page",// fallback for all the child routes
//     template: "%s | Auth ",// %s gets filled by page's title
//   },
//   description: "Generated by create next app",
// };
import Wrapper from "../wrapper-error";
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [input, setInput] = useState("")
    return (
        <>
            <Header />
            <input className="text-gray-800 bg-white" value={input} onChange={(e) => setInput(e.target.value)}></input>
            {/* this doesnt remount so we use template to remount for use cases like animation , useEffect fetches and so on , fresh start , state reset 
        just change this file to template.tsx
        you can also use both of them if required , layout's children is substituded by templaate and that of template by page.tsx
      */}
            <Wrapper />
            {children}

        </>

    );
}
