import type { Metadata } from "next";

import Header from "@/Components/Header";
import Footer from "@/Components/Footer";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    notifications,
    revenue,
    users,
    login
}: Readonly<{
    children: React.ReactNode;
    notifications: React.ReactNode;
    revenue: React.ReactNode;
    users: React.ReactNode;
    login: React.ReactNode;
}>) {
    const isLoggedin = true
    // parallel routes :
    //Note : these slots have their own route and state in a single layout so re-rendering is not ana issue for them , however their
    // routes are still "dashboard and dont have their own"
    // layout still runs without page in the directory as a route


    return isLoggedin ? (<>

        <Header />
        {children}
        {notifications}
        {revenue}
        {users}
        <Footer />/
    </>)
        : (
            login
        )

}
